name: Create release and deploy

on:
  workflow_dispatch:
    inputs:
      update_type:
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-release-and-deploy:
    uses: dtekcth/workflows/.github/workflows/create-release-and-deploy.yml@c30a8ecf6ebd1d4194869cb98458abfe1cd5e702 # v1.3.6
    permissions:
      contents: write
      packages: write
    with:
        update_type: ${{ inputs.update_type }}
