name: Create release and deploy

on:
  workflow_dispatch:
    inputs:
      update_type:
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-release-and-deploy:
    uses: dtekcth/workflows/.github/workflows/create-release-and-deploy.yml@49637020f4d7f23a0f4f2c41b50aac6cfa2cfc73 # v1.4.0
    permissions:
      contents: write
      packages: write
    with:
        update_type: ${{ inputs.update_type }}
