name: review
on:
  - pull_request
jobs:
  check:
    name: Compile and test
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.5' # Exact version of ghc to use

      - name: update cabal index
        run: |
          cabal v2-update -v

      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache
        uses: actions/cache/restore@v3
        with:
          key: ${{ runner.os }}-${{ github.sha }}
          path: ~/.cabal/store
          restore-keys: ${{ runner.os }}-

      - name: install dependencies
        run: cabal v2-build -v --enable-tests all --dependencies-only -j2 all

      - name: tests
        run: cabal v2-test --enable-tests all --test-show-details=direct

      - name: save cache
        uses: actions/cache/save@v3
        if: always()
        with:
          key: ${{ runner.os }}-${{ github.sha }}
          path: ~/.cabal/store
