name: Docker

on:
  push:
    tags: ["v*.*.*"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
            extra_nix_config: |
              trusted-public-keys = pingu.cachix.org-1:42+JuilNrMORsv7pUKCrpzAB5ykq1Y7XVEf+Wl8TVFg=
              substituters-extra = https://pingu.cachix.org

      - run: nix build .\#docker
      - run: docker load < ./result

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: mat-chalmers
          tags: ${{ steps.meta.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GITHUB_TOKEN }}
          password: ${{ secrets.GITHUB_TOKEN }}
