name: Publish Docker Image

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build-and-push-image:
    uses: dtekcth/workflows/.github/workflows/docker-publish.yml@v1.0.0
    permissions:
      contents: read
      packages: write
